// src/lib/mock-data.ts
export const MOCK_DIAL_PLAN = {
  businessContext: {
    name: "Bella's Pizza",
    type: "Restaurant",
    staffCount: 3,
    hours: "09:00-21:00",
    timezone: "Africa/Johannesburg",
  },
  dialPlan: {
    nodes: [
      {
        id: "entry",
        type: "entryPoint",
        label: "Call Arrives",
        simpleLabel: "Someone calls",
      },
      {
        id: "time_check",
        type: "timeCondition",
        label: "Opening Hours Check",
        simpleLabel: "Are we open?",
        config: { openHours: "09:00-21:00" },
      },
      {
        id: "welcome",
        type: "announcement",
        label: "Welcome Message",
        simpleLabel: "Play greeting",
      },
      {
        id: "call_group",
        type: "callGroup",
        label: "Ring All Staff",
        simpleLabel: "Ring everyone",
        config: { strategy: "simultaneous" },
      },
      {
        id: "voicemail",
        type: "voicemail",
        label: "After Hours Voicemail",
        simpleLabel: "Leave message",
      },
    ],
    edges: [
      { from: "entry", to: "time_check", condition: null },
      { from: "time_check", to: "welcome", condition: "open", label: "Yes" },
      { from: "time_check", to: "voicemail", condition: "closed", label: "No" },
      { from: "welcome", to: "call_group", condition: null },
      {
        from: "call_group",
        to: "voicemail",
        condition: "no_answer",
        label: "No Answer",
      },
    ],
  },
  mermaidSimple: `graph TD
    entry["Someone calls"] --> time_check["Are we open?"]
    time_check -->|"Yes"| welcome["Play greeting"]
    time_check -->|"No"| voicemail["Leave message"]
    welcome --> call_group["Ring everyone"]
    call_group -->|"No Answer"| voicemail`,
  mermaidTechnical: `graph TD
    entry["Call Arrives"] --> time_check["Opening Hours Check"]
    time_check -->|"Open"| welcome["Welcome Message"]
    time_check -->|"Closed"| voicemail["After Hours Voicemail"]
    welcome --> call_group["Ring All Staff"]
    call_group -->|"Timeout"| voicemail`,
  features: [
    {
      id: "voip_account",
      name: "VoIP Account",
      description:
        "VoIP account enables seamless connectivity with a variety of devices and softphones",
      helpUrl: "https://help.voys.co.za/voip-account",
      used: true,
    },
    {
      id: "users",
      name: "Users",
      description: "Configure how and where users can be reached",
      helpUrl: "https://help.voys.co.za/user-reachability",
      used: true,
    },
    {
      id: "phone_number",
      name: "Phone Number",
      description: "Assign phone numbers to your dial plan",
      helpUrl: "https://help.voys.co.za/phone-number",
      used: true,
    },
    {
      id: "opening_hours_basic",
      name: "Opening Hours Basic",
      description: "Set your business operating hours",
      helpUrl: "https://help.voys.co.za/opening-hours-basic",
      used: true,
    },
    {
      id: "call_group",
      name: "Call Groups",
      description: "Ring multiple users simultaneously or sequentially",
      helpUrl: "https://help.voys.co.za/callgroup",
      used: true,
    },
    {
      id: "messages",
      name: "Messages",
      description: "Manage and create audio messages for your dial plan",
      helpUrl: "https://help.voys.co.za/messages",
      used: true,
    },
    {
      id: "voicemail",
      name: "Voicemail",
      description: "Record messages when unavailable",
      helpUrl: "https://help.voys.co.za/voicemail",
      used: true,
    },
    {
      id: "music_on_hold",
      name: "Hold Music",
      description: "Transform waiting time into a pleasant experience",
      helpUrl: "https://help.voys.co.za/music-on-hold",
      used: false,
    },
    {
      id: "ivr",
      name: "IVR Menu",
      description: "Interactive voice menus (Press 1 for Sales)",
      helpUrl: "https://help.voys.co.za/ivr",
      used: false,
    },
    {
      id: "queue",
      name: "Call Queue",
      description: "Hold callers with music when busy",
      helpUrl: "https://help.voys.co.za/queue",
      used: false,
    },
    {
      id: "announcements",
      name: "Variable Announcements",
      description: "Play dynamic pre-recorded messages",
      helpUrl: "https://help.voys.co.za/variable-announcement",
      used: false,
    },
    {
      id: "caller_name",
      name: "Variable Caller Name",
      description: "Announce caller information",
      helpUrl: "https://help.voys.co.za/variable-caller-name",
      used: false,
    },
    {
      id: "call_recording",
      name: "Call Recording",
      description: "Record conversations for quality assurance",
      helpUrl: "https://help.voys.co.za/call-recording",
      used: false,
    },
    {
      id: "fixed_mobile",
      name: "Fixed-Mobile",
      description: "Link office and mobile numbers",
      helpUrl: "https://help.voys.co.za/fixed-mobile",
      used: false,
    },
    {
      id: "filter",
      name: "Filter",
      description: "Route calls based on caller phone number",
      helpUrl: "https://help.voys.co.za/filter",
      used: false,
    },
    {
      id: "sounds",
      name: "Sounds",
      description: "Upload and manage audio files",
      helpUrl: "https://help.voys.co.za/sounds",
      used: false,
    },
  ],
  voiceScripts: [
    {
      type: "welcome",
      text: "Thank you for calling Bella's Pizza. Please hold while we connect you.",
      duration: "5s",
    },
    {
      type: "voicemail",
      text: "You've reached Bella's Pizza. We are currently closed. Our hours are 11am to 9pm daily. Please leave a message and we'll call you back.",
      duration: "12s",
    },
  ],
  implementationSteps: [
    {
      step: 1,
      title: "Create Users (3 Staff)",
      description:
        "Add your staff members to the system. Each user gets an internal number (601, 602, 603) and 3 VoIP accounts per user.",
      actions: [
        "Go to Freedom Portal → Users",
        "Click 'Add' for each staff member",
        "Enter: First name, Last name, Email address",
        "Check 'Send email to user to create password'",
        "Select 'End-user' permission (for staff who only make/receive calls)",
        "Click Create/Save",
        "Note: User 1 (601) gets VoIP accounts 201, 202, 203",
        "User 2 (602) gets 204, 205, 206",
        "User 3 (603) gets 207, 208, 209",
      ],
      helpUrl: "https://freedom.voys.co.za/redirect/User",
      estimatedTime: "5 minutes",
    },
    {
      step: 2,
      title: "Configure Call Group",
      description:
        "Create a call group to ring all staff simultaneously when a call comes in.",
      actions: [
        "Go to Freedom Portal → Call Groups",
        "Click 'Add'",
        "Choose an extension number (suggested in blue)",
        "Select 'All at the same time' (simultaneous ringing)",
        "Add all 3 user email addresses under destinations",
        "Click Save",
      ],
      helpUrl: "https://freedom.voys.co.za/client/redirect/callgroup/",
      estimatedTime: "2 minutes",
    },
    {
      step: 3,
      title: "Set Opening Hours",
      description: "Define when your pizza shop is open for business.",
      actions: [
        "Go to Freedom Portal → Opening Hours (Basic)",
        "Set hours: Mon-Sun 11:00-21:00",
        "Click Next",
        "Select public holidays (calls will route to voicemail)",
        "Click Save",
      ],
      helpUrl: "https://freedom.voys.co.za/client/redirect/openinghoursbasic/",
      estimatedTime: "2 minutes",
    },
    {
      step: 4,
      title: "Create Welcome Message",
      description:
        "Record or upload your greeting that plays when customers call.",
      actions: [
        "Go to Freedom Portal → Messages",
        "Click 'Add'",
        "Name: 'Welcome Message'",
        "Select 'Add audio file' from dropdown",
        "Upload pre-recorded file OR record in browser",
        "Suggested text: 'Thank you for calling Bella's Pizza. Please hold.'",
        "Click Save",
      ],
      helpUrl: "https://freedom.voys.co.za/client/redirect/messages/",
      estimatedTime: "3 minutes",
    },
    {
      step: 5,
      title: "Setup Music On Hold",
      description: "Add pleasant music for customers while waiting.",
      actions: [
        "Go to Freedom Portal → Music On Hold",
        "Click 'Add'",
        "Name: 'Hold Music'",
        "Check 'Use in outgoing calls'",
        "Click Next",
        "Upload audio file (MP3 or WAV)",
        "Click Save",
      ],
      helpUrl: "https://freedom.voys.co.za/client/redirect/musiconhold/",
      estimatedTime: "3 minutes",
    },
    {
      step: 6,
      title: "Configure Voicemail",
      description: "Set up voicemail for after-hours and missed calls.",
      actions: [
        "Go to Freedom Portal → Voicemail",
        "Click 'Add'",
        "Name: 'After Hours Voicemail'",
        "Enter email addresses (comma-separated for multiple)",
        "You'll receive voicemails as .wav files + transcription",
        "Click Save",
      ],
      helpUrl: "https://freedom.voys.co.za/client/redirect/voicemail/",
      estimatedTime: "3 minutes",
    },
    {
      step: 7,
      title: "Build Your Dial Plan",
      description: "Connect all modules into a complete call routing system.",
      actions: [
        "Go to Freedom Portal → Routing (Dial Plans)",
        "Click 'Add Dial Plan'",
        "Enter phone number and description: 'Main Number'",
        "Click 'Save & Go to dial plan'",
        "Click 'Edit dial plan'",
        "STEP 1: Add 'Music On Hold' → Select your music",
        "STEP 2: Add 'Opening Hours Basic' → Select your hours",
        "Inside 'During opening hours':",
        "  → Add 'Messages' (your welcome message)",
        "  → Add 'Call Group' (your staff group, 20s ring time)",
        "  → Add 'Voicemail' (fallback if no answer)",
        "Inside 'Outside opening hours':",
        "  → Add 'Voicemail' (after hours message)",
        "Inside 'Public holidays':",
        "  → Add 'Voicemail' (holiday message)",
        "Click 'Save Dial Plan'",
      ],
      helpUrl: "https://freedom.voys.co.za/client/redirect/routing/",
      estimatedTime: "10 minutes",
    },
  ],
};
